[package]

name = "world"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
rustc-serialize = "0.3"
num = "0.1"
vec_map = "0.6"
rand = "0.3"

[dependencies.calx]
git = "https://github.com/rsaarelm/calx"
verson = "0.2"
branch = "0.2"
