[package]

name = "world"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

# TODO: Use crates.io version once it's updated
[dependencies.collect]
git = "https://github.com/Gankro/collect-rs"

[dependencies.rustc-serialize]

[dependencies.num]

[dependencies.rand]

[dependencies.rand_macros]

[dependencies.calx_util]
git = "https://github.com/rsaarelm/calx"
