[package]

name = "world"
version = "0.0.1"
authors = [ "risto.saarelma@iki.fi" ]

[lib]
name = "world"

[dependencies]
rustc-serialize = "0.3"
num = "0.1"
vec_map = "0.8"
rand = "0.3"

[dependencies.calx]
path = "../calx"
