[package]
name = "calx_ecs"
version = "0.2.0"
authors = ["Risto Saarelma <risto.saarelma@iki.fi>"]
description = "Rust entity component library"
keywords = ["gamedev", "ecs"]
license = "MIT"

[dependencies]
rustc-serialize = "0.3"
